CREATE TABLE admin (
  "id" number(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "username" varchar2(32) DEFAULT '' NOT NULL,
  "password" varchar2(255) DEFAULT '' NOT NULL,
  "name" varchar2(128) NOT NULL
)  ;

--
-- Đang đ? d? li?u cho b?ng `admin`
--

INSERT INTO admin ("username", "password", "name")
 SELECT 'nghiant', '$2y$10$224Hnp9vSsISaNhjnxXCB.cHZzf3DIoh4I22X37eoFAt1.EhCdgeq', 'Nguyễn Trung Nghĩa' FROM dual UNION ALL 
 SELECT 'linhdt', '$2y$10$D80l/f7aG3z9DK/vDm.lyeZcpPjgcA/IbRFiqB6KRgJKTLNTv2pRu', 'Dương Thùy Linh' FROM dual;
 
-- --------------------------------------------------------

--
-- C?u trúc b?ng cho b?ng `category`
--

CREATE TABLE category (
  "id" number(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "name" varchar2(128) NOT NULL,
  "parent_id" number(10) DEFAULT 0 NOT NULL,
  "sort_order" number(3) DEFAULT 0 NOT NULL
)  ;

INSERT INTO CATEGORY ("name","parent_id", "sort_order") VALUES ('Laptop', 0, 0);
INSERT INTO CATEGORY ("name","parent_id", "sort_order") VALUES ('Điện thoại', 0, 1);
INSERT INTO CATEGORY ("name","parent_id", "sort_order") VALUES ('Tivi', 0, 2);
INSERT INTO CATEGORY ("name","parent_id", "sort_order") VALUES (' Acer', 1, 0);
INSERT INTO CATEGORY ("name","parent_id", "sort_order") VALUES (' Apple', 1, 1);
INSERT INTO CATEGORY ("name","parent_id", "sort_order") VALUES ('Asus', 1, 2);
INSERT INTO CATEGORY ("name","parent_id", "sort_order") VALUES ('Dell', 1, 3);
INSERT INTO CATEGORY ("name","parent_id", "sort_order") VALUES ('HP', 1, 5);
INSERT INTO CATEGORY ("name","parent_id", "sort_order") VALUES ('Apple', 2, 0);
INSERT INTO CATEGORY ("name","parent_id", "sort_order") VALUES ('Asus', 2, 1);
INSERT INTO CATEGORY ("name","parent_id", "sort_order") VALUES ('BlackBerry', 2, 3);
INSERT INTO CATEGORY ("name","parent_id", "sort_order") VALUES ('HTC', 2, 4);
INSERT INTO CATEGORY ("name","parent_id", "sort_order") VALUES ('AKAI', 3, 0);
INSERT INTO CATEGORY ("name","parent_id", "sort_order") VALUES ('JVC', 3, 1);
INSERT INTO CATEGORY ("name","parent_id", "sort_order") VALUES ('LG', 3, 2);
INSERT INTO CATEGORY ("name","parent_id", "sort_order") VALUES ('Panasonic', 3, 3);
INSERT INTO CATEGORY ("name","parent_id", "sort_order") VALUES ('Samsung', 3, 5);
INSERT INTO CATEGORY ("name","parent_id", "sort_order") VALUES ('Toshiba', 3, 6);
 
 -- --------------------------------------------------------

--
-- C?u trúc b?ng cho b?ng `comments`
--

CREATE TABLE comments (
  "id" number(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "product_id" number(10) NOT NULL,
  "parent_id" number(10) NOT NULL,
  "user_name" varchar2(128) NOT NULL,
  "user_email" varchar2(100) NOT NULL,
  "user_id" number(10) NOT NULL,
  "content" clob NOT NULL,
  "created" timestamp(0) DEFAULT NULL NULL,
  "count_like" number(10) NOT NULL,
  "status" number(3) DEFAULT 0 NOT NULL
)  ;

-- --------------------------------------------------------


--
-- C?u trúc b?ng cho b?ng `orders`
--

CREATE TABLE orders (
  "transaction_id" number(10) NOT NULL,
  "id" number(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "product_id" number(10) NOT NULL,
  "qty" number(10) DEFAULT 0 NOT NULL,
  "amount" number(15,4) NOT NULL,
  "status" number(3) DEFAULT 0 NOT NULL
)  ;

-- --------------------------------------------------------

--
-- C?u trúc b?ng cho b?ng `product`
--

CREATE TABLE product (
  "id" number(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "category_id" number(10) NOT NULL,
  "name" varchar2(128) NOT NULL,
  "maker_id" number(10) NOT NULL,
  "price" number(15,4) DEFAULT 0 NOT NULL,
  "content" clob,
  "discount" number(10) DEFAULT 0 NOT NULL,
  "image_link" varchar2(50) NOT NULL,
  "image_list" clob,
  "created" timestamp(0) DEFAULT NULL NULL,
  "view" number(10) DEFAULT 0 NOT NULL,
  "warranty" varchar2(50) NOT NULL,
  "total" number(10) DEFAULT 0 NOT NULL,
  "buyed" number(10) DEFAULT 0 NOT NULL,
  "rate_total" number(10)DEFAULT 0 NOT NULL,
  "rate_count" number(10) DEFAULT 0 NOT NULL,
  "gifts" varchar2(100) NOT NULL,
  "video" varchar2(255) NOT NULL,
  "feature" number(10) DEFAULT 0 NOT NULL
)  ;

INSERT INTO product ("category_id", "name", "maker_id", "price", "content", "discount", "image_link", "image_list", "created", "view", "warranty", "total", "buyed", "rate_total", "rate_count", "gifts", "video", "feature") VALUES (15, 'Tivi LG 4000', 0, 4000000.0000, 'Bài vi?t cho s?n ph?m này đang đư?c c?p nh?t ...', 200000, 'product2.jpg', '',TIMESTAMP '2018-04-19 10:07:16', 4, '12 tháng', 0, 3, 4, 1, 'USB 4G', 'https://www.youtube.com/embed/zAEYQ6FDO5U', 0);
INSERT INTO product ("category_id", "name", "maker_id", "price", "content", "discount", "image_link", "image_list", "created", "view", "warranty", "total", "buyed", "rate_total", "rate_count", "gifts", "video", "feature") VALUES (13, 'Tivi Akai', 0, 5000000.0000, 'Bài vi?t cho s?n ph?m này đang đư?c c?p nh?t ...', 0, 'product1.jpg', '',TIMESTAMP '2018-04-19 10:07:16', 11, '12 tháng', 0, 4, 4, 1, 'USB 4G', 'https://www.youtube.com/embed/zAEYQ6FDO5U', 0);
INSERT INTO product ("category_id", "name", "maker_id", "price", "content", "discount", "image_link", "image_list", "created", "view", "warranty", "total", "buyed", "rate_total", "rate_count", "gifts", "video", "feature") VALUES (16, 'Tivi Panasonic', 0, 6000000.0000, 'Bài vi?t cho s?n ph?m này đang đư?c c?p nh?t ...', 0, 'product3.jpg', '',TIMESTAMP '2018-04-19 10:07:16', 4, '12 tháng', 0, 1, 12, 3, 'USB 4G', 'https://www.youtube.com/embed/zAEYQ6FDO5U', 0);
INSERT INTO product ("category_id", "name", "maker_id", "price", "content", "discount", "image_link", "image_list", "created", "view", "warranty", "total", "buyed", "rate_total", "rate_count", "gifts", "video", "feature") VALUES (17, 'Tivi Samsung', 0, 5500000.0000, 'Bài vi?t cho s?n ph?m này đang đư?c c?p nh?t ...', 0, 'product4.jpg', '',TIMESTAMP '2018-04-19 10:07:16', 1, '12 tháng', 0, 0, 0, 0, 'USB 4G', 'https://www.youtube.com/embed/zAEYQ6FDO5U', 0);
INSERT INTO product ("category_id", "name", "maker_id", "price", "content", "discount", "image_link", "image_list", "created", "view", "warranty", "total", "buyed", "rate_total", "rate_count", "gifts", "video", "feature") VALUES (15, 'Tivi LG 5000', 0, 5000000.0000, 'Bài vi?t cho s?n ph?m này đang đư?c c?p nh?t ...', 0, 'product5.jpg', '',TIMESTAMP '2018-04-19 10:07:16', 1, '12 tháng', 0, 0, 0, 0, 'USB 4G', 'https://www.youtube.com/embed/zAEYQ6FDO5U', 0);
INSERT INTO product ("category_id", "name", "maker_id", "price", "content", "discount", "image_link", "image_list", "created", "view", "warranty", "total", "buyed", "rate_total", "rate_count", "gifts", "video", "feature") VALUES (18, 'Tivi Toshiba', 0, 6200000.0000, 'Bài vi?t cho s?n ph?m này đang đư?c c?p nh?t ...', 400000, 'product6.jpg', '',TIMESTAMP '2018-04-19 10:07:16', 74, '12 tháng', 0, 0, 7, 2, 'USB 4G', 'https://www.youtube.com/embed/zAEYQ6FDO5U', 0);
INSERT INTO product ("category_id", "name", "maker_id", "price", "content", "discount", "image_link", "image_list", "created", "view", "warranty", "total", "buyed", "rate_total", "rate_count", "gifts", "video", "feature") VALUES (14, 'Tivi JVC 500', 0, 10000000.0000, 'Bài vi?t cho s?n ph?m này đang đư?c c?p nh?t ...', 500000, 'product7.jpg', '',TIMESTAMP '2018-04-19 10:07:16', 112, '12 tháng', 0, 0, 17, 5, 'USB 4G', 'https://www.youtube.com/embed/zAEYQ6FDO5U', 0);
INSERT INTO product ("category_id", "name", "maker_id", "price", "content", "discount", "image_link", "image_list", "created", "view", "warranty", "total", "buyed", "rate_total", "rate_count", "gifts", "video", "feature") VALUES (15, 'Tivi LG 520', 0, 5400000.0000, '<p>Bai vi?t cho s?n ph?m đang đư?c c?p nh?t ...</p>', 400000, 'product13.jpg', 'a:0:{}',TIMESTAMP '2018-04-19 10:07:16', 19, '12 tháng', 0, 0, 4, 1, '0', 'https://www.youtube.com/embed/zAEYQ6FDO5U', 0);
INSERT INTO product ("category_id", "name", "maker_id", "price", "content", "discount", "image_link", "image_list", "created", "view", "warranty", "total", "buyed", "rate_total", "rate_count", "gifts", "video", "feature") VALUES (9, 'iPhone X 64GB', 0, 32990000.0000, '', 90000, 'x-silver_1_2.jpg', '["finish_iphone-x_dark_gray_large_1_1.jpg","finish_iphone-x_silver_large_1_1.jpg","iphone-x-64gb-1-400x460.png","x-gray-back_1_1.png","x-silver-back_1_1.png"]',TIMESTAMP '2018-04-19 23:43:42', 9, '12 tháng', 0, 4, 0, 0, 'S?c d? ph?ng', 'https://www.youtube.com/embed/79LPrp6D3Is', 0);

-- --------------------------------------------------------

--
-- C?u trúc b?ng cho b?ng `transaction`
--

CREATE TABLE transactions (
  "id" number(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "type" number(3) DEFAULT 0 NOT NULL,
  "status" number(3) DEFAULT 0 NOT NULL,
  "user_id" number(10) DEFAULT 0 NOT NULL,
  "user_name" varchar2(50) NOT NULL,
  "user_email" varchar2(50) NOT NULL,
  "user_phone" varchar2(20) NOT NULL,
  "amount" number(15,4) DEFAULT 0 NOT NULL,
  "payment" varchar2(32) NOT NULL,
  "payment_info" varchar2(4000),
  "message" varchar2(255),
  "security" varchar2(16),
  "created" timestamp(0) DEFAULT NULL NULL
)  ;

CREATE TABLE userss (
  "id" number(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "name" varchar2(50) NOT NULL,
  "email" varchar2(50) NOT NULL,
  "phone" varchar2(15) NOT NULL,
  "address" varchar2(128) NOT NULL,
  "password" varchar2(255) NOT NULL,
  "created" timestamp(0) DEFAULT NULL NULL
)  ;

ALTER TABLE admin
  ADD PRIMARY KEY ("id");
  
ALTER TABLE category
  ADD PRIMARY KEY ("id");

ALTER TABLE comments
  ADD PRIMARY KEY ("id");
  
ALTER TABLE orders
  ADD PRIMARY KEY ("id");
  
ALTER TABLE product
  ADD PRIMARY KEY ("id");
  
ALTER TABLE transactions
  ADD PRIMARY KEY ("id");
  
ALTER TABLE userss
  ADD PRIMARY KEY ("id");
  
ALTER TABLE PRODUCT
ADD CONSTRAINT FK_CATEGORY
    FOREIGN KEY ("category_id") REFERENCES CATEGORY("id");

ALTER TABLE ORDERS
ADD CONSTRAINT FK_PRODUCT_ORDERS
    FOREIGN KEY ("product_id") REFERENCES PRODUCT("id");
ALTER TABLE ORDERS
ADD	CONSTRAINT FK_TRANSACTIONS_ORDERS
    FOREIGN KEY ("transaction_id") REFERENCES TRANSACTIONS("id");

ALTER TABLE COMMENTS
ADD CONSTRAINT FK_PRODUCT_COMMENTS
    FOREIGN KEY ("product_id") REFERENCES PRODUCT("id");
ALTER TABLE COMMENTS
ADD CONSTRAINT FK_USERSS_COMMENTS
    FOREIGN KEY ("user_id") REFERENCES USERSS("id");

ALTER TABLE TRANSACTIONS
ADD CONSTRAINT FK_USERSS_TRANSACTIONS
    FOREIGN KEY ("user_id") REFERENCES USERSS("id");